### PR TITLE
Check for Private Functions

### PR DESCRIPTION
**Pull request by johnakos**
Check for private functions that are not intended for use by plugin and theme developers, but only by other core functions.

### CODE REVIEW

**Comment by Otto42** [comment]
Why these functions in particular? Do we have a current issue where themes are using these that we need to prevent?

**Comment by johnakos** [comment]
I think yes.
https://codex.wordpress.org/Category:Private_Functions

From wordpress.org codex

> 
This function's access is marked as private. That means it is not intended for use by plugin and theme developers, but only in other core functions. It is listed here for completeness

**Comment by Otto42** [comment]
Yes, I get that. However, do you have any examples of any themes actually using these in a way that we need to detect for the review process?

Theme Check isn't meant to check everything possible, nor can it. It's a tool for our reviewers. It only aims to solve currently occurring problems.

**Comment by Otto42** [comment]
Closing as there is no reason for this at this time.

**Pull request closed without merging**
